### ISSUE TITLE
.next return wrong date

### ISSUE THREAD

**Issue by eric8words** [6tail/lunar-flutter#12]
var s = Solar.fromYmd(2023, 10, 24).next(5);print(s);//2023-10-29
    var t = Solar.fromYmd(2023, 10, 24).next(6);print(t);//2023-10-29

**Comment by eric8words** [comment]
It may be due to UTC.

Duration.InDays() works incorrect (?) #32431

**Comment by eric8words** [comment]
The following code can resolve the issue. Thank you !

    DateTime c = ExactDate.fromYmdHms(_year, _month, _day, _hour, _minute, _second);
    return Solar.fromDate(DateTime(c.year, c.month, c.day + days));

**Comment by 6tail** [comment]
v1.3.0 fixed it and removed ExactDate.
