### ISSUE TITLE
可以有繁體字嗎?

### ISSUE THREAD

**Issue by eric8words** [6tail/lunar-flutter#13]
Is it possible to provide traditional chinese output ? Thank You !

**Comment by 6tail** [comment]
v1.6.0起将支持多语言。

**Comment by xuanyunhui** [comment]
> v1.6.0起将支持多语言。

会支持英文吗？

**Comment by 6tail** [comment]
会，但是我翻译不全，有些需要自行补充。

**Comment by 6tail** [comment]
> > v1.6.0起将支持多语言。
> 
> 会支持英文吗？


会，但是我翻译不全，有些需要自行补充。

**Comment by eric8words** [comment]
> v1.6.0起将支持多语言。

Thank you !

**Comment by xuanyunhui** [comment]
> > > v1.6.0起将支持多语言。
> > 
> > 
> > 会支持英文吗？
> 
> 会，但是我翻译不全，有些需要自行补充。

@6tail 英文支持进行了可以呼我，我们有一部分现成的翻译。

**Comment by 6tail** [comment]
> > > > v1.6.0起将支持多语言。
> > > 
> > > 
> > > 会支持英文吗？
> > 
> > 
> > 会，但是我翻译不全，有些需要自行补充。
> 
> @6tail 英文支持进行了可以呼我，我们有一部分现成的翻译。

英文都快翻译完了。。

**Comment by 6tail** [comment]
> > > > v1.6.0起将支持多语言。
> > > 
> > > 
> > > 会支持英文吗？
> > 
> > 
> > 会，但是我翻译不全，有些需要自行补充。
> 
> @6tail 英文支持进行了可以呼我，我们有一部分现成的翻译。

可以帮忙校正一下已有的翻译。[https://6tail.cn/calendar/i18n-messages.html](https://6tail.cn/calendar/i18n-messages.html)
