### ISSUE TITLE
文档似乎打不开了

### ISSUE THREAD

**Issue by dujianchi** [6tail/lunar-flutter#20]
`https://6tail.cn/calendar/api.html`文档地址似乎打不开，我换了好几种网络环境了，才来提交的issue

**Comment by 6tail** [comment]
我访问正常。

**Comment by dujianchi** [comment]
我全局开梯子访问是正常打开了😂不然真的打不开（福建电信4G/5G/宽带都不行，以及一台腾讯轻量云windows服务器都没打开，好像是报connection_reset），因为我本地梯子默认设置了绕过大陆，切全局就可以访问了
