### ISSUE TITLE
可以增加節氣時間轉換月份嗎？

### ISSUE THREAD

**Issue by eric8words** [6tail/lunar-flutter#7]
可以增加節氣時間轉換月份嗎？如立春時間是新曆2月4日，11:00 am. 則 11:00 am過後為一月。可以嗎?這個時間點是需要查表的。

**Comment by 6tail** [comment]
目前是支持11:00 am后为新的月干支，你看是否可以按正月起寅的规则，用地支来转换月份。请参考：http://6tail.cn/calendar/api.html#lunar.ganzhi.html

**Comment by 6tail** [comment]
节气时间点，不需要查表，已动态计算至9999年。

**Comment by eric8words** [comment]
謝謝你!
